
# <-- Events-->


backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "What's On Events"
    folder: "content/events"

    create: true
    slug: "{{slug}}"

    extension: "json"
    format: "json"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"
        time_format: false
        format: "D MMMM YYYY"

      - label: "Location"
        name: "location"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Image"
        name: "image"
        widget: "image"

      - label: "Website Link"
        name: "link"
        widget: "string"
        required: false

# <-- Regular Users -->

  - name: "users"
    label: "Regular Users"
    folder: "content/users"

    create: true
    slug: "{{slug}}"

    extension: "json"
    format: "json"

    fields:
      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Image"
        name: "image"
        widget: "image"

      - label: "Short Information"
        name: "summary"
        widget: "text"

      - label: "Modal Description"
        name: "description"
        widget: "markdown"

      - label: "Contact"
        name: "contact"
        widget: "string"
        required: false

      - label: "Website"
        name: "website"
        widget: "string"
        required: false